{
 "title": "3D-Drucker",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "3D-Drucker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Maschine",
   "type": "singlestat",
   "description": "Name der Maschine",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "format": "h",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  name\nFROM\n  prim_werkzeuge\nWHERE \n  id_prim_werkzeug=1"
    }
   ]
  },
  {
   "title": "Hersteller",
   "type": "singlestat",
   "description": "Hersteller der Maschine",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 1 },
   "format": "h",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  hersteller\nFROM\n  maschinen\nWHERE \n  id_maschine=1"
    }
   ]
  },
  {
   "title": "Baujahr",
   "type": "singlestat",
   "description": "Baujahr der Maschine",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  baujahr\nFROM\n  maschinen\nWHERE \n  id_maschine=1"
    }
   ]
  },
  {
   "title": "Beschreibung",
   "type": "singlestat",
   "description": "Beschreibung der Maschine",
   "gridPos": { "h": 2, "w": 5, "x": 11, "y": 1 },
   "format": "h",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  beschreibung\nFROM\n  maschinen\nWHERE \n  id_maschine=1"
    }
   ]
  },
  {
   "title": "Farbe",
   "type": "singlestat",
   "description": "Farbe der Maschine",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "format": "h",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  farbe\nFROM\n  maschinen\nWHERE \n  id_maschine=1"
    }
   ]
  },
  { "title": "Alarmen", "type": "alertlist", "description": "Status der Maschine.", "gridPos": { "h": 6, "w": 5, "x": 0, "y": 3 } },
  {
   "title": "3D-Druckerleistung",
   "type": "singlestat",
   "description": "Leistung des 3D-Druckers",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 3 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  'Spindelleistung' AS metric,\n  wert\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 6\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "3D-Druckerleistung",
   "type": "graph",
   "description": "Leistung des 3D-Druckers",
   "gridPos": { "h": 5, "w": 12, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  '3D-Druckerleistung' AS metric,\n  wert\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 6\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Filamentverbrauch",
   "type": "singlestat",
   "description": "Filamentfüllung",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 8 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  wert\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 12\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Druckbetttemperatur",
   "type": "singlestat",
   "description": "Temperatur des Druckbetts",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 8 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  wert\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 8\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Druckbetttemperatur",
   "type": "graph",
   "description": "Temperatur des Druckbettes über die Zeit",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  wert AS \"Temperatur\"\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 8\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Betriebsstunden",
   "type": "singlestat",
   "description": "Maschinenlaufzeit",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 9 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(id_prim_werkzeug,$__interval),\n  sum(laufzeit) AS \"laufzeit\"\nFROM prim_werkzeuge\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "letzte Wartung vor",
   "type": "singlestat",
   "description": "Zeit seit letzter Wartung",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 11 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  laufzeit\nFROM services\nWHERE id_service=1\n"
    }
   ]
  },
  {
   "title": "Wartung",
   "type": "text",
   "description": "Bestätigen Sie hier bitte, wenn die Führungen geölt und gefettet wurden.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 13 },
   "content": "<iframe src=\"http://localhost/Wartung.php\" height=\"100%\" width=\"100%\" frameBorder=\"0\"></iframe>"
  },
  {
   "title": "Werkzeugauswahl",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 13 },
   "content": "<iframe src=\"http://localhost/werkzeugwahl.php\" height=\"100%\" width=\"100%\" frameBorder=\"0\"></iframe>"
  },
  {
   "title": "Maschinenleistung",
   "type": "singlestat",
   "description": "Leistung der Maschine",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 13 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  'Maschinenleistung' AS metric,\n  wert\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 7\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Maschinenleistung",
   "type": "graph",
   "description": "Überprüfung vom Leerlauf",
   "gridPos": { "h": 5, "w": 7, "x": 13, "y": 13 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  'Maschinenleistung' AS metric,\n  wert\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 7\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  '3D-Druckerleistung' AS metric,\n  wert\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 6\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Beschleunigung",
   "type": "graph",
   "description": "Beschleunigung in x-, y- und z-Richtung",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  'x-Richtung' AS metric,\n  wert\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 9\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  'y-Richtung' AS metric,\n  wert\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 10\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  'z-Richtung' AS metric,\n  wert\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 11\nORDER BY 1,2"
    }
   ]
  },
  { "title": "Live Streaming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Live Streaming",
   "type": "text",
   "description": "Video Streaming in Echtzeit von der Maschine",
   "gridPos": { "h": 16, "w": 20, "x": 0, "y": 25 },
   "content": "<iframe src=\"http://192.168.42.110:8081/\" height=\"100%\" width=\"100%\" frameBorder=\"0\"></iframe>"
  },
  {
   "title": "Smart Services (3D-Drucker)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wartung",
     "type": "graph",
     "description": "Zeit bis nächste Wartung",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  laufzeit\nFROM services\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_service = 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Filament",
     "type": "graph",
     "description": "Überwachung des Filaments",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  wert\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 12\nORDER BY 1"
      }
     ]
    }
   ]
  }
 ]
}