{
 "title": "Spindel",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Maschine1_Spindel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Maschine",
   "type": "singlestat",
   "description": "Name der Maschine",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "format": "h",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  name\nFROM\n  prim_werkzeuge\nWHERE \n  id_prim_werkzeug=2"
    }
   ]
  },
  {
   "title": "Hersteller",
   "type": "singlestat",
   "description": "Hersteller der Maschine",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 1 },
   "format": "h",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  hersteller\nFROM\n  maschinen\nWHERE \n  id_maschine=1"
    }
   ]
  },
  {
   "title": "Baujahr",
   "type": "singlestat",
   "description": "Baujahr der Maschine",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  baujahr\nFROM\n  maschinen\nWHERE \n  id_maschine=1"
    }
   ]
  },
  {
   "title": "Beschreibung",
   "type": "singlestat",
   "description": "Beschreibung der Maschine",
   "gridPos": { "h": 2, "w": 5, "x": 11, "y": 1 },
   "format": "h",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  beschreibung\nFROM\n  maschinen\nWHERE \n  id_maschine=1"
    }
   ]
  },
  {
   "title": "Farbe",
   "type": "singlestat",
   "description": "Farbe der Maschine",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "format": "h",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  farbe\nFROM\n  maschinen\nWHERE \n  id_maschine=1"
    }
   ]
  },
  {
   "title": "Betriebslaufzeit",
   "type": "singlestat",
   "description": "Maschinenlaufzeit",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 3 },
   "format": "clocks",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  laufzeit \nFROM maschinen\nWHERE\n  id_maschine = 1"
    }
   ]
  },
  {
   "title": "Spindelleistung",
   "type": "singlestat",
   "description": "Leistung der Spindel",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 3 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  'Spindelleistung' AS metric,\n  wert\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 6\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Spindelleistung",
   "type": "graph",
   "description": "Leistungen des Spindels",
   "gridPos": { "h": 5, "w": 12, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  'Spindelleistung' AS metric,\n  wert\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 6\nORDER BY 1,2"
    }
   ]
  },
  { "title": "Alarms", "type": "alertlist", "description": "Status der Maschine", "gridPos": { "h": 7, "w": 5, "x": 0, "y": 5 } },
  {
   "title": "4mm Fräser Verbrauch",
   "type": "singlestat",
   "description": "Betriebsstunden des Werkzeugs",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 8 },
   "format": "clocks",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  laufzeit\nFROM\n  sek_werkzeuge\nWHERE \n  id_sek_werkzeug=1"
    }
   ]
  },
  {
   "title": "Fräser 6 mm Verbrauch",
   "type": "singlestat",
   "description": "Betriebsstunden des Werkzeugs",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 8 },
   "format": "clocks",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  laufzeit\nFROM\n  sek_werkzeuge\nWHERE \n  id_sek_werkzeug=2"
    }
   ]
  },
  {
   "title": "Werkzeugtemperatur",
   "type": "singlestat",
   "description": "Temperatur des Werkzeugs",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 8 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  wert\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 8\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Werkzeugtemperatur",
   "type": "graph",
   "description": "Temperatur des Werkzeugs über die Zeit",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  wert AS \"Temperatur\"\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 8\nORDER BY 1"
    }
   ]
  },
  {
   "title": "letzte Wartung vor",
   "type": "singlestat",
   "description": "Zeit seit letzter Wartung",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 12 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  laufzeit\nFROM services\nWHERE id_service=1\n"
    }
   ]
  },
  {
   "title": "Wartung",
   "type": "text",
   "description": "Bestätigen Sie hier bitte, wenn die Führungen geölt und gefettet wurden.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 14 },
   "content": "<iframe src=\"http://localhost/Wartung.php\" height=\"100%\" width=\"100%\" frameBorder=\"0\"></iframe>"
  },
  {
   "title": "Werkzeugauswahl",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 14 },
   "content": "<iframe src=\"http://localhost/werkzeugwahl.php\" height=\"100%\" width=\"100%\" frameBorder=\"0\"></iframe>"
  },
  {
   "title": "Maschinenleistung",
   "type": "singlestat",
   "description": "Leistung der Maschine",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 14 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  'Maschinenleistung' AS metric,\n  wert\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 7\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Maschinenleistung",
   "type": "graph",
   "description": "Überprüfung vom Leerlauf",
   "gridPos": { "h": 5, "w": 7, "x": 13, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  wert\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 7\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Beschleunigung",
   "type": "graph",
   "description": "Beschleunigung in x-, y- und z-Richtung",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  'x-Richtung' AS metric,\n  wert\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 9\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  'y-Richtung' AS metric,\n  wert\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 10\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  'z-Richtung' AS metric,\n  wert\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 11\nORDER BY 1,2"
    }
   ]
  },
  { "title": "Live Streaming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Live Streaming",
   "type": "text",
   "description": "Video Streaming in Echtzeit von der Maschine",
   "gridPos": { "h": 16, "w": 20, "x": 0, "y": 26 },
   "content": "<iframe src=\"http://192.168.42.110:8081/\" height=\"100%\" width=\"100%\" frameBorder=\"0\"></iframe>"
  },
  {
   "title": "Smart Services (Spindel)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wartung",
     "type": "graph",
     "description": "Zeit bis nächste Wartung",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  laufzeit\nFROM services\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_service = 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "4mm-Fräser Überwachung",
     "type": "graph",
     "description": "Überwachung des 4mm-Fräsers",
     "gridPos": { "h": 4, "w": 7, "x": 6, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  id_prim_werkzeug AS \"time\",\n  id_prim_werkzeug\nFROM sek_werkzeuge\nWHERE\n  $__unixEpochFilter(id_prim_werkzeug)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "6mm-Fräser Überwachung",
     "type": "graph",
     "description": "Überwachung des 6mm-Fräsers",
     "gridPos": { "h": 4, "w": 7, "x": 13, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  laufzeit\nFROM services\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_service = 6\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Maschine2_3D-Drucker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Maschine",
     "type": "singlestat",
     "description": "Name der Maschine",
     "gridPos": { "h": 2, "w": 5, "x": 0, "y": 23 },
     "format": "h",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  name\nFROM\n  prim_werkzeuge\nWHERE \n  id_prim_werkzeug=1"
      }
     ]
    },
    {
     "title": "Hersteller",
     "type": "singlestat",
     "description": "Hersteller der Maschine",
     "gridPos": { "h": 2, "w": 4, "x": 5, "y": 23 },
     "format": "h",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  hersteller\nFROM\n  maschinen\nWHERE \n  id_maschine=1"
      }
     ]
    },
    {
     "title": "Baujahr",
     "type": "singlestat",
     "description": "Baujahr der Maschine",
     "gridPos": { "h": 2, "w": 2, "x": 9, "y": 23 },
     "format": "h",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  baujahr\nFROM\n  maschinen\nWHERE \n  id_maschine=1"
      }
     ]
    },
    {
     "title": "Beschreibung",
     "type": "singlestat",
     "description": "Beschreibung der Maschine",
     "gridPos": { "h": 2, "w": 5, "x": 11, "y": 23 },
     "format": "h",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  beschreibung\nFROM\n  maschinen\nWHERE \n  id_maschine=1"
      }
     ]
    },
    {
     "title": "Farbe",
     "type": "singlestat",
     "description": "Farbe der Maschine",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 23 },
     "format": "h",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  farbe\nFROM\n  maschinen\nWHERE \n  id_maschine=1"
      }
     ]
    },
    { "title": "Alarms", "type": "alertlist", "description": "Status der Maschine", "gridPos": { "h": 8, "w": 5, "x": 0, "y": 25 } },
    {
     "title": "Maschinenleistung",
     "type": "singlestat",
     "description": "Leistung der Maschine",
     "gridPos": { "h": 5, "w": 3, "x": 5, "y": 25 },
     "format": "watt",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  'Maschinenleistung' AS metric,\n  wert\nFROM sensordaten\nWHERE\n  id_sensor = 7\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "3D-Druckerleistung",
     "type": "singlestat",
     "description": "Leistung des 3D-Druckers",
     "gridPos": { "h": 5, "w": 3, "x": 8, "y": 25 },
     "format": "watt",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  'Spindelleistung' AS metric,\n  wert\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 6\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "3D-Druckerleistung",
     "type": "graph",
     "description": "Leistung des 3D-Druckers",
     "gridPos": { "h": 5, "w": 9, "x": 11, "y": 25 },
     "yaxes": [
      { "format": "watt" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  '3D-Druckerleistung' AS metric,\n  wert\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 6\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Filamentverbrauch",
     "type": "singlestat",
     "description": "Filamentfüllung",
     "gridPos": { "h": 5, "w": 3, "x": 5, "y": 30 },
     "format": "watt",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\n  id_daten AS \"time\",\n  id_daten\nFROM sensordaten\nWHERE\n  $__unixEpochFilter(id_daten)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Druckbetttemperatur",
     "type": "singlestat",
     "description": "Temperatur des Druckbetts",
     "gridPos": { "h": 5, "w": 3, "x": 8, "y": 30 },
     "format": "celsius",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\n  wert\nFROM\n  sensordaten\nWHERE \n  id_sensor=8"
      }
     ]
    },
    {
     "title": "Druckbetttemperatur",
     "type": "graph",
     "description": "Temperatur des Druckbettes über die Zeit",
     "gridPos": { "h": 5, "w": 9, "x": 11, "y": 30 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  wert AS \"Temperatur\"\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 8\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Betriebsstunden",
     "type": "singlestat",
     "description": "Maschinenlaufzeit",
     "gridPos": { "h": 2, "w": 5, "x": 0, "y": 33 },
     "format": "dtdurations",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__unixEpochGroupAlias(id_prim_werkzeug,$__interval),\n  sum(laufzeit) AS \"laufzeit\"\nFROM prim_werkzeuge\nGROUP BY 1\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Smart Services (3D-Drucker)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wartung",
     "type": "text",
     "description": "Bestätigen Sie hier bitte, wenn die Führungen geölt und gefettet wurden.",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 24 },
     "content": "<iframe src=\"http://localhost/Wartung.php\" height=\"100%\" width=\"100%\" frameBorder=\"0\"></iframe>"
    },
    {
     "title": "Wartung",
     "type": "graph",
     "description": "Zeit bis nächste Wartung",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  laufzeit\nFROM services\nWHERE\n  $__unixEpochFilter(zeitstempel) AND\n  id_service = 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Maschinenleistung",
     "type": "graph",
     "description": "Überprüfung vom Leerlauf",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  zeitstempel AS \"time\",\n  wert\nFROM sensordaten\nWHERE\n  $__timeFilter(zeitstempel) AND\n  id_sensor = 7\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Werkzeugauswahl",
     "type": "text",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 29 },
     "content": "<iframe src=\"http://localhost/werkzeugwahl.php\" height=\"100%\" width=\"100%\" frameBorder=\"0\"></iframe>"
    },
    {
     "title": "Filament",
     "type": "graph",
     "description": "Überwachung des Filaments",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    }
   ]
  }
 ]
}